openapi: 3.0.1
info:
  title: mini-bank API
  version: 1.0.1
servers:
  - url: /
paths:
  /bank/v1/accounts:
    get:
      summary: Gets an array of accounts
      description: Gets an array of accounts
      responses:
        200:
          description: Gets an array of accounts
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
    put:
      summary: Put an account
      description: Put an account
      operationId: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Account'
        required: true
      responses:
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
  /bank/v1/account/{id}:
    get:
      summary: Gets an account
      description: Gets a account
      operationId: getAccountById
      parameters:
        - name: id
          in: path
          description: ID of account that needs to be fetched
          required: true
          schema:
            maximum: 10000.0
            minimum: 1.0
            type: integer
            format: int64
      responses:
        200:
          description: Gets a account
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Account'
        404:
          description: Account not found
          content: {}
  /bank/v1/users:
    get:
      summary: Gets an array of users
      description: Gets an array of users
      responses:
        200:
          description: Gets an array of users
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    put:
      summary: Update an user
      description: Update an user
      operationId: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
    post:
      summary: Save an user
      description: Save an user
      operationId: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        405:
          description: Invalid input
          content: { }
      x-codegen-request-body-name: body
      delete:
        summary: Delete an user
        description: Delete an user
        operationId: ""
        requestBody:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
          required: true
        responses:
          405:
            description: Invalid input
            content: { }
        x-codegen-request-body-name: body
  /bank/v1/user/{id}:
    get:
      summary: Gets an user
      description: Gets a user
      operationId: getUserById
      parameters:
        - name: id
          in: path
          description: ID of user that needs to be fetched
          required: true
          schema:
            maximum: 10000.0
            minimum: 1.0
            type: integer
            format: int64
      responses:
        200:
          description: Gets a user
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: User not found
          content: {}
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        lastName:
          type: string
        surName:
          type: string
        userName:
          type: string
        email:
          type: string
        password:
          type: string
    Account:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        Number:
          type: string
        openDate:
          type: string
          format: date-time
        closeDate:
          type: string
          format: date-time
        status:
          type: string
          description: Account Status
          enum:
            - open
            - hold
            - close
