name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build-java:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Package
        run: mvn -B clean package -DskipTests


         
